export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const POST_MODEL = 'POST_MODEL';
export const USER_MODEL = 'USER_MODEL';
export const COMMENT_MODEL = 'COMMENT_MODEL';
export const FILM_MODEL = 'FILM_MODEL';
export const RATING_MODEL='RATING_MODEL';
